# Import the colorscheme I want to use
import = ["~/.config/alacritty/kanagawa_dragon.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"

[window]
opacity = 0.70
padding ={ x = 6, y = 6 }

[scrolling]
history = 10000

[font]
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
size = 14.00
