# Import the colorscheme I want to use
import = ["~/.config/alacritty/kanagawa_wave.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"

[window]
opacity = 1.00
padding ={ x = 15, y = 15 }

[scrolling]
history = 10000

[font]
normal = { family = "Iosevka nerd font", style = "medium" }
italic = { family = "Iosevka nerd font", style = "medium oblique" }
bold = { family = "Iosevka nerd font", style = "extrabold" }
size = 12.00
